name: container build
on:
  push:
    branches: main

jobs:
  container-build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      # we need a checkout here, because we have local actions
      - name: checkout
        uses: actions/checkout@v2
      - name: generate short sha
        id: short-sha
        uses: ./.github/actions/short-sha
        with:
          long-sha: ${{ github.sha }}
      # https://github.com/docker/login-action
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # https://github.com/docker/build-push-action
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.short-sha.outputs.short-sha }},ghcr.io/${{ github.repository }}:latest
